services:
  backend:
    image: IMAGE_NAME
    container_name: BACKEND_CONTAINER_NAME
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - net
  db:
    image: postgres:latest
    container_name: POSTGRES_CONTAINER_NAME
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./uploads:/app/uploads
    ports:
      - "5432:5432"
    networks:
      - net

networks:
  net:
    driver: bridge