services:
  backend:
    image: IMAGE_FRONTEND_NAME
    container_name: BACKEND_CONTAINER_NAME
    depends_on:
      - db
    ports:
      - "8000:8080"
    networks:
      - net
  db:
    image: postgres:latest
    container_name: POSTGRES_CONTAINER_NAME
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./uploads:/app/uploads
    ports:
      - "5432:5432"
    networks:
      - net

  frontend:
    image: IMAGE_FRONTEND_NAME
    container_name: FRONTEND_CONTAINER_NAME
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:3030"
    networks:
      - net
    depends_on:
      - backend

networks:
  net:
    driver: bridge